version: '3.10'

services:
  backend:
    build: ./
    command: > # sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2"
      sh -c "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8001:8000"
    depends_on:
      - db
      - migration
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - backend
    
  migration:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend

  celery:
    build: ./
    restart: always
    command: celery -A config worker -l info
    volumes: 
      - ./:/usr/src/app/
    depends_on:
      - backend
      - redis
    networks:
      - backend


  redis:
    image: redis
    restart: always
    ports:
      - "6378:6379"
    networks:
      - backend



  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    container_name: "flagman-nginx"
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/conf.d/nginx-local.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - backend
    networks:
      - backend



volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend: